<?
	$styles = array(
		'main_logo' => '/fbmmlogo.gif',
		'main_site' => "/index.html",
		'title' => 'FBMM',
		'name' => 'Foggy Bottom',
		'bgcolor' => '#ffffff',
		'color' => '#7A1712',
		'a_link' => '#D47A13',
		'a_visited' => '#D17810',
		'a_hover' => '#366dba',
		'a_tentative' => '#D47A13',
		'a_canceled' => '#aaaaaa',
		'hr_color' => '#366dba',
	);
	
	$dojo_path = "http://ajax.googleapis.com/ajax/libs/dojo/1.2.3/";
?>
