<?
$attendees['6o9um5cjhh5srl6tsr5dqsti7o'] = array(
    'Jim_Besser' => array('status' => 'Music', 'guests' => 0),
    'Bill_Brown' => array('status' => 'Maybe', 'guests' => 0),
    'Nathaniel_Brown' => array('status' => 'No', 'guests' => 0),
    'Alex_Dennis' => array('status' => 'Maybe', 'guests' => 0),
    'Brad_Graham' => array('status' => 'Yes', 'guests' => 0),
    'Meyer_Kachel' => array('status' => 'Yes', 'guests' => 0),
    'Andrew_Marcus' => array('status' => 'Yes', 'guests' => 0),
    'Jud_McIntire' => array('status' => 'Maybe', 'guests' => 0),
    'Alan_Peel' => array('status' => 'Yes', 'guests' => 0),
    'Hal_Rogoff' => array('status' => 'Yes', 'guests' => 0),
    'Art_Shaw' => array('status' => 'Yes', 'guests' => 0),
    'Rodger_Sunderland' => array('status' => 'Maybe', 'guests' => 0),
    'Jim_Voorhees' => array('status' => 'No', 'guests' => 0)
)
?>
