<?
$attendees['d00h9s068a23mb8eis6sjtv2do'] = array(
    'Jim_Besser' => array('status' => 'Music', 'guests' => 0),
    'Bill_Brown' => array('status' => 'Yes', 'guests' => 0),
    'Alex_Dennis' => array('status' => 'Yes', 'guests' => 0),
    'Brad_Graham' => array('status' => 'Yes', 'guests' => 0),
    'Meyer_Kachel' => array('status' => 'No', 'guests' => 0),
    'Mike_Livingston' => array('status' => 'No', 'guests' => 0),
    'Andrew_Marcus' => array('status' => 'Yes', 'guests' => 0),
    'Jud_McIntire' => array('status' => 'No', 'guests' => 0),
    'Alan_Peel' => array('status' => 'Yes', 'guests' => 0),
    'Art_Shaw' => array('status' => 'No', 'guests' => 0),
    'Rodger_Sunderland' => array('status' => 'Maybe', 'guests' => 0),
    'Jim_Voorhees' => array('status' => 'Maybe', 'guests' => 0)
)
?>
