<?
$attendees['d41pa40temjnftoh19k9rmvvs4'] = array(
    'Jim_Besser' => array('status' => 'Music', 'guests' => 0),
    'Nathaniel_Brown' => array('status' => 'No', 'guests' => 0),
    'Brad_Graham' => array('status' => 'Yes', 'guests' => 0),
    'Mike_Livingston' => array('status' => 'No', 'guests' => 0),
    'Jud_McIntire' => array('status' => 'No', 'guests' => 0),
    'Alan_Peel' => array('status' => 'Yes', 'guests' => 0),
    'Art_Shaw' => array('status' => 'Yes', 'guests' => 0),
    'Jim_Voorhees' => array('status' => 'Yes', 'guests' => 0)
)
?>
