<?
$attendees['fpe5dnbj5qti6qbiv1ifv73d4g'] = array(
    'Jim_Besser' => array('status' => 'Music', 'guests' => 0),
    'Nathaniel_Brown' => array('status' => 'Yes', 'guests' => 0),
    'Alex_Dennis' => array('status' => 'Yes', 'guests' => 0),
    'Brad_Graham' => array('status' => 'Yes', 'guests' => 0),
    'Mike_Livingston' => array('status' => 'Yes', 'guests' => 0),
    'Jud_McIntire' => array('status' => 'Maybe', 'guests' => 0),
    'Alan_Peel' => array('status' => 'Yes', 'guests' => 0),
    'Art_Shaw' => array('status' => 'Yes', 'guests' => 0),
    'Rodger_Sunderland' => array('status' => 'Yes', 'guests' => 0)
)
?>
