<?
$attendees['gljididvb6d42fj6e7jrmd89gc'] = array(
    'Jim_Besser' => array('status' => 'Music', 'guests' => 0),
    'Bill_Brown' => array('status' => 'Yes', 'guests' => 0),
    'Brad_Graham' => array('status' => 'Yes', 'guests' => 1),
    'Meyer_Kachel' => array('status' => 'Yes', 'guests' => 0),
    'Mike_Livingston' => array('status' => 'Yes', 'guests' => 1),
    'Jud_McIntire' => array('status' => 'Maybe', 'guests' => 0),
    'Alan_Peel' => array('status' => 'Maybe', 'guests' => 0),
    'Steven_Roth' => array('status' => 'Maybe', 'guests' => 1),
    'Abroad:_Colin_Sandel' => array('status' => 'Yes', 'guests' => 0),
    'Rodger_Sunderland' => array('status' => 'Maybe', 'guests' => 0),
    'MIA:_Steven_Roth__Z' => array('status' => 'Maybe', 'guests' => 1)
)
?>
