<?
$attendees['ledimaql906ssi644p9ag02u14'] = array(
    'Jim_Besser' => array('status' => 'Music', 'guests' => 0),
    'Bill_Brown' => array('status' => 'Maybe', 'guests' => 0),
    'Alex_Dennis' => array('status' => 'Yes', 'guests' => 0),
    'Brad_Graham' => array('status' => 'Yes', 'guests' => 0),
    'Meyer_Kachel' => array('status' => 'No', 'guests' => 0),
    'Jud_McIntire' => array('status' => 'Maybe', 'guests' => 0),
    'Alan_Peel' => array('status' => 'Yes', 'guests' => 0),
    'Steven_Roth' => array('status' => 'Maybe', 'guests' => 1),
    'Art_Shaw' => array('status' => 'Yes', 'guests' => 0),
    'Rodger_Sunderland' => array('status' => 'Maybe', 'guests' => 0)
)
?>
