<?
$attendees['mf24md8v9p8ouf6b2igsf6mhe8'] = array(
    'Jim_Besser' => array('status' => 'Music', 'guests' => 0),
    'Bill_Brown' => array('status' => 'Leave early', 'guests' => 0),
    'Nathaniel_Brown' => array('status' => 'No', 'guests' => 0),
    'Alex_Dennis' => array('status' => 'Maybe', 'guests' => 0),
    'Brad_Graham' => array('status' => 'Leave early', 'guests' => 0),
    'Meyer_Kachel' => array('status' => 'Yes', 'guests' => 0),
    'Jim_Lewis' => array('status' => 'No', 'guests' => 0),
    'Mike_Livingston' => array('status' => 'No', 'guests' => 0),
    'Andrew_Marcus' => array('status' => 'Yes', 'guests' => 0),
    'Jud_McIntire' => array('status' => 'Yes', 'guests' => 0),
    'Alan_Peel' => array('status' => 'Yes', 'guests' => 0),
    'Art_Shaw' => array('status' => 'Yes', 'guests' => 0),
    'Rodger_Sunderland' => array('status' => 'Maybe', 'guests' => 0),
    'Gus_Voorhees' => array('status' => 'Yes', 'guests' => 0)
)
?>
