<?
$attendees['t2deph3e8bmsnejuat4nh5e75c'] = array(
    'Jim_Besser' => array('status' => 'Yes', 'guests' => 0),
    'Bill_Brown' => array('status' => 'Maybe', 'guests' => 0),
    'Meyer_Kachel' => array('status' => 'Yes', 'guests' => 0),
    'Mike_Livingston' => array('status' => 'No', 'guests' => 0),
    'Jud_McIntire' => array('status' => 'Maybe', 'guests' => 0),
    'Alan_Peel' => array('status' => 'Yes', 'guests' => 0),
    'Rodger_Sunderland' => array('status' => 'Maybe', 'guests' => 0)
)
?>
