<?
$attendees['tae8fi878i7moplm98nim0tn1k'] = array(
    'Jim_Besser' => array('status' => 'No', 'guests' => 0),
    'Bill_Brown' => array('status' => 'Yes', 'guests' => 0),
    'Nathaniel_Brown' => array('status' => 'No', 'guests' => 0),
    'Brad_Graham' => array('status' => 'Maybe', 'guests' => 0),
    'Meyer_Kachel' => array('status' => 'Yes', 'guests' => 0),
    'Mike_Livingston' => array('status' => 'Yes', 'guests' => 0),
    'Jud_McIntire' => array('status' => 'Maybe', 'guests' => 0),
    'Alan_Peel' => array('status' => 'Yes', 'guests' => 0),
    'Joe_Shelby' => array('status' => 'Yes', 'guests' => 0),
    'Rodger_Sunderland' => array('status' => 'Maybe', 'guests' => 0)
)
?>
