<?
$attendees['tlj6vrugev7nhucr85j2u7s22g'] = array(
    'Jim_Besser' => array('status' => 'Music', 'guests' => 0),
    'Bill_Brown' => array('status' => 'Yes', 'guests' => 0),
    'Nathaniel_Brown' => array('status' => 'Yes', 'guests' => 0),
    'Alex_Dennis' => array('status' => 'Yes', 'guests' => 0),
    'Brad_Graham' => array('status' => 'Yes', 'guests' => 0),
    'Meyer_Kachel' => array('status' => 'Yes', 'guests' => 0),
    'Jim_Lewis' => array('status' => 'Yes', 'guests' => 0),
    'Mike_Livingston' => array('status' => 'Yes', 'guests' => 0),
    'Andrew_Marcus' => array('status' => 'No', 'guests' => 0),
    'Jud_McIntire' => array('status' => 'Maybe', 'guests' => 0),
    'Alan_Peel' => array('status' => 'Yes', 'guests' => 0),
    'Hal_Rogoff' => array('status' => 'No', 'guests' => 0),
    'Art_Shaw' => array('status' => 'Yes', 'guests' => 0),
    'Cyd_Shelby' => array('status' => 'Arrive late', 'guests' => 0),
    'Joe_Shelby' => array('status' => 'Arrive late', 'guests' => 0),
    'Rodger_Sunderland' => array('status' => 'Yes', 'guests' => 0)
)
?>
