<?
$attendees['uqr2go391mljlmuh7bmv42tm3c'] = array(
    'Nathaniel_Brown' => array('status' => 'Yes', 'guests' => 0),
    'Brad_Graham' => array('status' => 'Yes', 'guests' => 0),
    'Meyer_Kachel' => array('status' => 'Yes', 'guests' => 0),
    'Mike_Livingston' => array('status' => 'No', 'guests' => 0),
    'Andrew_Marcus' => array('status' => 'Yes', 'guests' => 0),
    'Jud_McIntire' => array('status' => 'Maybe', 'guests' => 0),
    'Alan_Peel' => array('status' => 'Yes', 'guests' => 0),
    'Hal_Rogoff' => array('status' => 'Yes', 'guests' => 0),
    'Art_Shaw' => array('status' => 'Yes', 'guests' => 0),
    'Cyd_Shelby' => array('status' => 'Maybe', 'guests' => 0),
    'Joe_Shelby' => array('status' => 'Yes', 'guests' => 0),
    'Rodger_Sunderland' => array('status' => 'Maybe', 'guests' => 0),
    'Jim_Besser' => array('status' => 'Music', 'guests' => 0)
)
?>
