<?
$details = "The kit: FBMM Casual; FBMM white based T-shirt, khakis, brown tie shoes (or brown flip-flops), royal blue neck scarf


Meet at Hard Times Cafe (N. Highland at Wilson Blvd across from Clarendon Metro)
7:00 for those eating
7:30 for those having one beer
8:00 for those just dancing
(the back room of Hard Times is under construction and they will only seat full parties. Get there as early as possible. If you can\\\'t abide Chili, try the Clarendon Grill or the New Spyder Kelly\\\'s))

8:00 Dance across the street at the office bldg plaza (Wilson Blvd &  
N. Highland St.)

Grab a quick beer at Whitlows for those with terrible thirst (Whitlow\\\'s becomes not kid* friendly after 9pm)

8:45PM Dance at plaza next to Baja Fresh (2815 Clarendon Blvd.) across  
from the Market Place & Whole Foods (Clarendon Blvd. & N. Edgewood )

9:30 Dance at Court House Metro (rain) or Four Provinces on Wilson  
(shine)

Optional: Visit the former site of Bardo (now demolished) and weep

10:00PM Retire to Four Provinces for kid* friendly snacks, beer (&  
song?)

    *kid = person under the age of 21 without false ID

Getting there:
Metro: Orange Line; Starting point Clarendon, departure, Court House

Parking: The Arlington County Health & Human Services (HHS) has free  
parking in a building at Wilson & N. Highland (our first dance stop).  
The ramp to the underground garage is on Highland street opposite the  
church. There\\\'s also free parking in the County office building on  
Clarendon Blvd near Court House (2100?), otherwise there\\\'s street  
parking as you find it. Do not park in any private lots. You will be  
towed!! (to Nick!)"
?>
