<?
$details = "Andrew and Sarah are getting married, in Rochester NY.   Here\\\'s how we imagine this working:

Those members of Foggy Bottom who are interested will dance around Rochester during the day on Saturday.  You are invited to attend the (short) ceremony Saturday evening, will perform a surprise dance at the reception at around 8:45pm.

On Sunday, we are having an outdoor picnic and jam session, to which Foggs are welcome."
?>
