<?
$details = "Effing Cold.  Dress warmly.  Start with Cotswold to get blood flowing!!! Gazebo order: General Taylor, Abbotts, Tun Dish & Mummers, interspersed with sword and yakking at the audience.  Library: Abbotts, Tun Dish, General Taylor and Mummers, interspersed with yakking.

Gazebo Run:  call time 6, check General Taylor chorus and start dancing as soon as we have a side and CE are there.  

1) General Taylor (song) leading to dance
2) Cutting Edge
3) Abbotts/Thaxted Horn Dance
4) Yak yak yak
5) Tun Dish
6) Cutting Edge
7) Mummer\\\'s Play  JLewis: Caller, Bill or Hal: DD, TT:?  Alan or Jud: PG, Brad: TS, Nathan: Dr. Art: Xmas.  We have need of a Twing Twang!!!  Joe did both caller and TT for REvels and it worked...Jim Lewis?

Library Run: arrive by 7:20, start dancing as soon as drummer guy is turfed out.
1) Abbotts/Thaxted Horn Dance
2) Yak yak yak
3) Tun Dish
4) Yak yak yak
5) General Taylor (song) leading to dance (too bad about the carpet)
6) Yak yak yak
7) Mummer\\\'s Play  JLewis or Joe Shelby: Caller, Bill or Hal: DD, TT: Steve  Alan or Jud: PG, Brad: TS, Nathan: Dr., Art: Xmas. 

Back to Bill\\\'s by 8:15ish."
?>
