<?
$details = "Friday, April 1
British Pub Night Concert with Brian Peters
Join British songster Brian Peters as he presents a lively evening of songs from his extensive repertoire to reflect the occasion; songs of foolery, trickery, magic and other devilment... as well as a stunning selection of instrumental tunes on the melodeon and concertina from his home in the north of England. Hicks with Sticks Morris will be on hand with beverages and light snacks to complement program... and there\\\'s a good chance there will be an impromptu English Ceilidh dance to follow. Come out for a rare evening of old English fun at the Shepherdstown Train Station! Admission is $15 adults, $12 seniors, $10 SMD members.Â  For more information call Joanie at (304) 263-2531 or email updf@earthlink.net, on the web at www.smad.us .

Saturday April 2
Fools Day of Dance
Join Hicks and other sides for a day of Border inspired foolery in Shepherdstown, Martinsburg and the surrounding area.
10AM Dance on the McMurran Lawn (to greet all guests)
Rest of the day TBA... Likely stands in Martinsburg at the Library, Veterans Hospital and War Memorial ParkÂ 
Lunch and Pub Stop at Good Natured Cafe http://www.goodnaturedllc.com/?page_id=12
Possible tour and tasting of DeFluri\\\'s Chocolates http://www.defluris.com/main/factory
5PM Final stand on King Street
Pub Stop and Dinner at Blue Moon Restaurant
8PM Contra Dance with Beverly Smith and The Rhythm Method String Band at the War Memorial Building

Sunday April 3:
Breakfast with your host and a final stand near the Shepherdstown Farmers Market

All weekend guests will be hosted with team members if they choose.Â  First-come-first-served.Â  Details forthcoming."
?>
