<?
$details = "Submit items for the agenda by December 31st or they will likely not be discussed!
Agenda:
1. Old Business
a. Foreman\\\'s Report
b. Ass\\\'t Bagman\\\'s Report
c. Bagman\\\'s Report
d. Squire\\\'s Report

2. Election of New (maybe) Officers

3. New Business
a. long term planning for upcoming Gigs
b. reminders on how to use the planner effectively
c. new practice space
d. recruitment/publicity
e. other (general kvetching)"
?>
