<?
$details = "1. Be at the gazebo by 5:45 am or else!
2. The post breakfast spot is likely the 5K run at the Community Center 410 East West HWY x Maple Ave in Tak Pak
3. Between that and Revels, we may spend a lot of time at Mary Chor\\\'s house singing and carousing (she lives about 1 mile away from Audubon).
4. When we\\\'ve danced at May Revels, the tour is officially over, though we are welcome to stick around and help Revels with Padstow for the 2nd show later in the afternoon...
4? Alternatively, we\\\'ll repair to Union Jack\\\'s in Bethesda if a Caps game isn\\\'t going on."
?>
