<?
$details = "3:30 tech, but we don\\\'t need much tech. Stay tuned. Foreman will pick two dances (tho we may only have time for one if that) and the Mummer\\\'s Play. Call time: 7 pm for anyone not doing tech.

We\\\'ll be performing sometime after 7:30(ish) in rotation. We actually only have 15 minutes of performing time, but should hang about in solidarity with the ballet girls and Chinese acrobats and so on."
?>
