<?
$details = "Party is in Takoma Park from 4:30 to 7:30 pm and will involve many adults (probably more adults than kids).  Liam is fascinated and obsessed with Morris dancing and this would tickle him no end.  

This is a paying gig.  We need four yesses (and a musician).

The goal would be to arrive by 5:30, entertain by teaching and demoing (not unlike the TPFF where Liam saw us again recently) for an hour.


Sarah Jane Marcus is making a mini set of bellpads for us to present to Liam as a gift."
?>
