<?
$details = "FULL KIT; BRING MASKS. Report to Cheverly Publick Playhouse by 3:23:24. We will run over the figures of Dilwyn/Fanny Frail in the parking lot thoroughly before our audition slot. Please confirm if you\\\'re coming! Expect it to be a 1/2 hour commitment on site (10 minute audition). Franklin\\\'s after for those that will to quench thirst.
Cheverly Publick Playhouse is where we just had the PARC dance in November; this will also be the theater where the performances occur on March 17th.
The performance date won\\\'t require us to use the same people, so that\\\'s a separate sign up."
?>
