<?
$details = "Shepherdstown May Day Celebration! May 6-8, 2010

Friday, May 6
Dinner and Bonfire with Singing, a screening of Morris:A Life with Bells On! for those who wish.

Saturday, May 7 Shepherdstown May Celebration
Probable order of Events
8AM Set up Maypole and Train Station for Lunch
10 AM Dance on the McMurran Lawn (to greet guests)
Morning Munch... Coffee and Snacks on the wall.
11:30 Line up for May Day Parade to the Rumsey Monument
12Noon Parade to Rumsey Monument followed by Revelry on the Green
Â Â  (see photo galleries at http://smad.us/gallery/ for more info as to what that is like)
1:30PM Catered Lunch at the Shepherdstown Train Station
2:30PM Dance at the Bavarian Inn
4PM Pub Stop at the Blue Moon
6PM Dinner at the Train Station
8PM Contra Dance with Anna Rain and Magic Foot at the War Memorial Building
Â Â  or Impromptu Singing and Ceilidh at the Train Station

Sunday, May 8
Brunch with hosts
Dance out at scenic location (to be disclosed later)... for those who will.
"
?>
