<?
$details = "Larry Robinson is turning 70 and his daughter is throwing a HUGE surprise party (yeah, like he\\\'s not gonna see this coming) at the Silver Spring Civic Center. She has requested that we make an appearance and do a few dances. This party will be a major event for folkies in the area and there\\\'s promise of some remuneration for the team. 
This is at the same time as Mike & Heather\\\'s holiday party, but we\\\'re not needed for very long - we could make a surgical, strategic strike from Mike\\\'s house and be back in time for more 12th night festivities at Mike & Heather\\\'s."
?>
