<?
$details = "We are a go.  We\\\'ll be joined by four other teams: Dread Pirate Rappers, Arlington Ladies, the Creekers and Cutting Edge.  The fest itself opens at noon and you are encouraged to come early.  Official call time is 1:30 with some individuals excused on account of their being involved with actual events on site from 1-2 (Bruce).  

We will dance at 2 and 4 with a hefty break in the middle.  Pubstop at Olive Lounge after (exact time TBD - but with mucho plenty of time to head back for contra)."
?>
