<?
$details = "This event will be border and sword.   Swords will be provided, for those who already know the dances from last year.   Bring your border mask, and a flat cap if you\\\\\\\\\\\'re dancing sword.

we will start by gathering at king street blues at noon.

we will practice sword a couple of times throught before we do it at the fountain.


do not park on the street alexnadria tickets and tows.best bet is to park under the fountain square. tour tour gathers at king street blues (112 North Saint Asaph Street, north side of the fountain square) between 11:30 and 12 noon at the bar.we practice the dances outside a couple of timesthen perform at the fountain square. (the hat shop no longer exist no traditional hat purchasing stop)then perform at the torpedo factory. (outside then inside weather permitting)then we ajourn to the union street pub at 4:30-5:00-ish "
?>
