<?
$details = "From Jud:
Start at Hard Times if you want dinner.  Don\\\'t get there any later than 7.  Otherwise, dancing starts at 8 across the street on the paved area at Highland and Wilson Blvd.

After nine PM the restaurants/ bars require a 21 ID so that limits us. It might be fun to pop into the Galaxy Hut before the second stand, but that might leave Gus on the curb playing his fiddle for a few bucks. We usually dance on the plaza at Baja Fresh next and then head to the Court House Metro stop before retiring to the Four Courts of Ireland, noisy but no ID required."
?>
