<?
$details = "This is a PAID GIG!   It is important that we have a good showing.

Be there at 7pm.   There is a \\\"sound check\\\" at 4pm.   Some of us will need to be there. i got our time for the sound check pushed to 5pm. be there before 5pm, we will do a whole run through of the show. same running order as takoma park library gig.


 got the sound check/lingting run through pushed off until 5pm. be there before 5pm.we will do the same running order as takoma park library gig. The theater is located at 3601 Powder Mill Rd., Beltsville, MD.
6th International Celebration of International Dance
January 10,2009, 7:30 p.m.
High Point High School
Double Click the attachment to view the slidePass this email on.....
Happy New Year!"
?>
