<?
$details = "Call time for FSGW is 12 noon on Saturday June 4th. Plan on wrapping up dancing by 3:45 at the latest.

In related news, Glyn and Andrew are playing from 1:45-2:15 and Frog Hammer (the English Ceildihghe3gx Band) plays at 4 pm

We start committing morris, hopefully in rotation with Arlington NW at 12:15 pm until 1:15, followed by a break.

At the 1:15 break, you can join me wherever my car is located for a tailgate. I shall bring cheese & crackers, G&T makings as well as cold beer.

Post refreshments, we shoud go watch Glyn stroke his instrument, backed up by Andrew. Hmmm. Should probably rephrase that.

Then another rotation from 2:30 until 3:34:25 or we feel bushed. Then go support Frog Hammer at 4."
?>
