<?
$details = "The Revels performances are 2 and 7:30, so between-show period is probably about 4:30 - 6.  AP will update this info after this weekend (and is down as \\\"Arrive Late\\\" because he can only be at the Revels stop for obvious reasons).

2:30: If you want lunch, meet at Lindy\\\'s Red Lion (2040 I Street NW)
3:30: Do a stand or two in the plaza behind the Lisner auditorium
4:15: Dance on the south side of the Lisner main entrance as patrons depart the theater
4:45: Crash the cast picnic on stage
5:00: Disperse and pretend like nothing happened.

This is a full kit event."
?>
