<?
$details = "ALL DETAILS YET TO BE CONFIRMED:
INFECVNDVS CAMPVS CVSPI (Fells Point Tour)
Saturday, 5 November 2011 Fells Point, Baltimore, MD
Foggy Bottom Morris Men, Arlington Ladies et Rock Creek Morris Women Salteravint Biberint et Cantiterint!
itineris
12:30-1:15 pm Bond Street Wharf
1:15-2:00 pm Duda\\\'s Tavern
2:00-3:00 pm Red Square
3:00-4:00 pm John Stevens, Ltd.
4:00-5:15 pm The Wharf Rat
5:30-6:00 pm South Broadway Wharf
6:02 pm Sunset Mass Dance
6:10-8:30 pm CONVIVIVM IN EXTREMIS Feast at The Waterfront Hotel
8:30 pm Bertha\\\'s Mussels for those that will (sing, continue carousing)
CONVIVIUM IN EXTREMIS
Served Buffet Style* with cash bar.
~ Cheese Platter – Van Gogh (semi-hard, nutty flavor), blue affime, four year aged cheddar, fontina, and gruyere, on a platter decorated with grapes, strawberries and seeded flatbread crackers.
~ Grilled Marinated Veggies – red onions, green and yellow squash and peppers grilled and served at room temperature.
~ Mussels – jumbo mussels steamed with white wine, onions, butter and fresh herbs.
~ Tacos – a trio of braised chicken tacos with chipotle adobo sauce, smoked yellowfin tuna tacos with southern corn relish, and black bean tacos with queso de Oaxaca.
~ Veggie Pasta – capatavi with marinated vegetables in a white wine butter sauce.
~ Chicken Pasta – capatavi with blackened chicken in a white wine butter sauce.
~ Steak satay with chimichurri sauce."
?>
