<?
$details = "National Press Club event: Sir Terry Pratchett will be coming to the National Press Club to celebrate the launch of the 39th Discworld book, Snuff, on October 14 at 7pm

Pratchett famously wrote about \\\"the other morris\\\" and he invented the \\\"mop and bucket dance\\\" in his Diskworld books. Morris teams often turn out to perform outside venues where he makes appearances.    --Bill

http://press.org/news-multimedia/news/satirist-terry-pratchett-introduces-latest-discworld-book-7-pm-oct-14

Stick and Bucket Dance: http://wiki.lspace.org/wiki/Stick_and_Bucket_Dance

A Stick and Bucket Dance/Dr Who version 
http://www.youtube.com/watch?v=7nFl_zwjbLA"
?>
