<?
$details = "We will start at the Wheaton Library (at Georgia Ave & Arcola).  The plan is to start dancing about 10:30, so teams should show up a little before that (but not too much, as the library does not open until 10:00).  About noon we will have lunch at the Limerick Pub in Wheaton (more on this below).  From there we will go to a nursing home (I have the one from last year in place--which is where I will likely send you guys, but am working on a second to be able to split the group up) about 2:15.  About 3:30 we will congregate in downtown Silver Spring.  My hope is to dance some outside (if it is mild enough).  We will then retire to McGinty\\\'s (we will go there directly if it is not warm enough to dance outside).  The day should rap up about 5:00.

As for lunch, the Limerick Pub will be doing a buffet for us.  It will be $15 (this includes tax and tip).  The main courses offered will be a Chicken w/marsala sauce, a grilled salmon, and a meat-less loaf with a wild mushroom sauce.  There will be sides of salad, cooked vegetable, and mash potatoes.  Soda, tea, & coffee will be included.  beer, wine, etc. can be purchased indiviually.
"
?>
