<?
$details = "The usual madrigals, maypole and morris gig.  Afternoon only, and we\\\'ll hit Colonel Brooks or Franklin\\\'s afterwards.
Deadline for voting: February 25th. This has not been the most popular event for the team in the past (two years ago we had a 4-side and I think we skipped it last year), but it is an event we should seriously consider for political reasons...and if not this one, then May 2nd (oy!)."
?>
