<?
$details = "Gents:
Cutting Edge is planning a low-key afternoon of guerilla dance at Eastern Market on March 20.  They\\\'d be pleased to have Foggy Bottom join \\\'em.  People in the Capitol Hill neighborhood have started a new monthly dance in the north Hall of the market building. It is still finding its footing, experimenting with format. They plan to perform at least one dance during a break of that dance.  The rest of the time we will be outside.

From David Roodman: \\\"We’re thinking of starting at 2pm, dancing, hanging out, dancing, then an early potluck dinner (+song and music?) at my place for those who will. I’m at 1231 C St. NE, which is walkable from Eastern Market.\\\"

The tentative schedule for the social dance in the north hall is:
1:00 to 2:00 pm   Two Rivers School sing-along performance 
2:00 to 3:00 pm   Family Square Dance for all ages
3:00 to 5:00 pm   Adult Square- and Contra-Dance

Cutting Edge was thinking of performing during a break in the 2-3pm slot, so the kids can see us all."
?>
