<?
$details = "Gents: we\\\'re possibly starting at Highland View to help demonstrate cardiovascular activity of one sort or another; the Science Faire goes from 7-8:30, so we (or at least some of us!) should aim to get there by 7:30ish. After we do whatever they\\\'d like us to do, we can head out and practice at Veteran\\\'s Plaza in Silver Spring, then head to McGinty\\\'s or Firestation 1. We\\\'ll talk about it at practice tonight (2/17)"
?>
