<?
$details = "Tedious Details: READ YOUR F***ING EMAILS FOR UPDATES

(currently in flux):

Travel dates:
Thursday/Friday 6/23-24 DC - Utrecht flight (+ train)
or Thursday 6/23 DC - London overnight flight + rail/sail ferry
Sunday 6/26 Hook - Harwich ferry (+ train)
Wednesday-Thursday 6/29-6/30 Southampton/Isle of Wight
Friday-Sunday Cambridge 7/1-3
Sunday 7/3 Heathrow car?

Lodging:
Friday/Saturday billeting 6/24 (if nec.) & 6/25 in Utrecht
Wednesday 6/29 billeting in Southampton
Thursday 6/30 billeting in Isle of Wight
Friday, Saturday nights: billeting/lodging Cambridge/Peterborough

Free dates for you to plan regarding travel/lodging:
Sunday 6/26 (may need to find your own lodging?)
most of Wednesday 6/29 (but lodging should be covered)
Friday - Sunday 7/1-7/3
"
?>
