<?
$details = "Details below this simple outline: (but use link above for full minifest grid). Only the \\\"*\\\" are \\\"required\\\" for a YES voter:

12:00 Foggs as ringers in the gym for AL workshop
* 1:00 dance in hallway per usual in rotation with others
2:00 break
* 3:00 dance in hallway per usual in rotation with others
3:45-4:15 Andrew & Glyn in cafetorium
4:15 maybe one more rotation, maybe not?
5:00 Froghammer in the main gym - be there!
7:30 Glen Echo Open Band if you wanna contra

At least some of us should be there by noon to be ringers for the Arlington Ladies NW morris workshop. Otherwise, calltime is 12:30 for 1 pm dance. I\\\'m assuming many AL\\\'s will want to do ECD at 2:00, so we should all remeet for dancing at 3; Andrew has to bugger off at 3:30 and we should quite at 3:45 to catch his show with Glyn in the cafetorium. If we still have a side and interest, dance again at 4:15 (maybe one final rotation?). Then Fogghammer...uh, I mean Froghammer at 5."
?>
