<?
$details = "Red Herring Morris holds a day of dance of Saturday, followed by a separate day of dance at the Arnold Arboretum on Sunday with all the Boston teams.

We have been invited to this several times in the past, but have not yet gotten up a side to do it.

If we do this, we will not do Marlboro, though London is still possible.   Vote \\\"Yes\\\" for your top choice event, \\\"Probably\\\" for second choice."
?>
