<?
$details = "Be there at 11:30 am!   The singing session starts promptly at 12.  

You may choose to attend the contra dance from 2-3.   Andrew Marcus, David Knight and Charlie Pilzer will be playing, and Anna Rain will be calling.

The goal of the singing session is to expose non-morris people to the unique style of singing that we do.  We want the session to be a showcase of our spontaneous singing style, but at the same time we want it to be accessible to those who don\\\'t know the words.

Please send Bill the lyrics to any songs you may wish to lead.  He will assemble them all into a booklet that participants will be able to use.  There will be no particular order to the songs; you may sing whenever the mood strikes you.  But please try to limit your songs to ones you\\\'ve already sent Bill.   And please announce what song you\\\'re singing before you start, so our non-morris friends can find it in their books.

In generally, try to choose songs that have good choruses, and that you can complete in under 3 minutes (everyone wants a turn)."
?>
