<?
$details = "The Tour will take place the weekend of September 25-27, and will include points of interest throughout the Boston and west-of-Boston area.  We have also invited the Toronto Morris Men, and may set up some dance opportunities/social opportunities with other area teams that often dance the same weekend.  We will be providing lodgings and some meals for teams that join us from afar."
?>
