<?
$details = "For now, sign up if you can make at least THREE of these FOUR shows.  We\\\'ll sort out an actual schedule by late October/Early November.  You should also plan on being at Tech Week at least Wednesday and Thursday nights, preferably more.

1st weekend: calltime probably an hour before each show (cast is 2-2.5 hours prior to show!)

Friday outreach:   7:30 pm
Saturday 1st show: 2:00 pm
         2nd show: 7:30 pm
Sunday   3rd show: 2:00 pm"
?>
