<?
$details = "We are committed!   This is a fun ale; we went a few years ago and had a great time.  Forest City will be there, which is always a plus.  ;-)

For those who want to figure out how to get to the Stevenson\\\'s Children\\\'s Camp (seems appropriate for Morris, eh?) from Buffalo, Ann Arbor or the DC area, here\\\'s the maplink on google:

http://maps.google.com/maps?near=Dorchester,+Thames+Centre,+ON,+Canada&geocode=&q=stevenson+children\\\'s+camp,&f=l&sll=42.989518,-81.058588&sspn=0.007424,0.013733&ie=UTF8&ll=43.018957,-81.070004&spn=0.056227,0.109863&t=h&z=13&iwloc=A

The Bagmobile (bagman\\\'s car) will be heading out for Harrisburg, PA to pick up Simon no later than 6:44:32 am (the crack of hell-o-clock, in other words) on Friday, June 5th.  If you\\\'re planning on being in that car, contact Alan at (301) 920-1912 asap to arrange it and to discuss food, music and driving details.
-----------------------------------------------------------------
Details:
The wait is over!  Join us for the annual London Morris Ale.  Good Cheer; warm hospitality and old friends, what more do you need?

St. Mary\\\'s Quarry Girls and Forest City Morris and Sword proudly present the 2009 LONDON MORRIS ALE.  Come and dance with the world\\\'s greatest Morris Dancers, share some great song, experience the fabulous food, enjoy a drink or two......or three.  Isn\\\'t this where YOU want to be on the weekend of Friday June 5 - Sunday June 7, 2009?

Our home base will once again be The Stevenson Children\\\'s Camp, located in delightful Dorchester Ontario.  This a full service camp, with enough cabins to accommodate over 100 people, also with plenty of space for those who wish to tent.  There are three cabins with their own washroom facilities, great for family with small children.  If you are interested in these cabins, they are on a first come first serve basis, so, sign up early!

The rest of the camp is fully equipped with washroom and shower facilities, hiking trails, playground equipment, as well as a baseball diamond, soccer field, basketball court, and volleyball court.  Need I say more?

Let us give you a preview of the weekend events:

    * Friday: receive guests from 5 - 6. *Light* dinner 6:30 Morris time
    * Registration: 7 - 9, in the dining hall
    * Saturday Morning: Continental breakfast
    * Tours head into the downtown core of Lovely London
    * Saturday afternoon: Massed stand at The Covent Garden Market www.coventmarket.com
    * Saturday evening: Cocktail Party and Feast back at the camp
    * Contra Dance, bonfire, singing
    * Sunday morning: Hot brunch.  Come hungry and well rested as there will be plenty of time to sleep in!
    * Sunday afternoon: Tours and Pub stops in Superb Stratford, Ont. www.stratford-canada.com
    * Back to camp for more food, merriment and memories.
    * Tearful goodbyes for those leaving us Sunday, some more rest for the weary travelers of Monday.

*Light* is a relative term.

 We look forward to seeing all of you, and hope that with your help this will be our best Ale ever, one that you look forward to every year!  Please remember to pack your tankard(s), we wouldn\\\'t want you missing out on your consumption possibilities by enduring under sized disposable cups!

Here are a few important details about the Ale:

DATE: Friday June 5 - Sunday June 7, 2009
PLACE: Stevenson Children\\\'s Camp
REGISTRATION FEE: Adults: $75
                                   Children 5 - 12 Yrs. $25
                                   Children under 5 Yrs. FREE
TEAM DEPOSIT: $150

Please note the following dates:

RSVP DEADLINE: February 28, 2009
TEAM DEPOSIT DEADLINE: March 31, 2009
CONFIRMATION OF TEAM NUMBERS CONSTITUTING YOUR FULL SIDE, MUSICIANS AND GUESTS: April 30, 2009
"
?>
