<?
$details = "Thanks to everyone who voted!  I know it\\\'s asking a lot, but this is our first paying gig of 2010 (we will earn $225). We will head over after the official part of our May tour is over at 2:30 in Adams Morgan.  We\\\'ll do two dances, lead a parade and finish with one dance by about 4:15.  Those who join us are welcome to head to Nanny O\\\'Brien\\\'s for a pint on me afterwards before heading home to rest.

The question mark will stay on this gig so that it remains off our public calendar.
Your Grateful Squire."
?>
