<?
$details = "The Revels shows are at 2 and 7:30.

We arrive at 4:30; dance for people coming out of the afternoon show; invade the theater and dance on stage for the performers\\\' dinner (Mummer\\\'s Play & Tun Dish?); head back outside and dance for people coming for the 2nd show. Dinner after at Lindy\\\'s Red Lion. 

Diehards are welcome to stay and crash the Bertucci\\\'s run after 2nd show is over."
?>
