<?\n$details = "As promised, here is the specific info for the December 3 Strathmore Mansion concert where you and the Foggies will debut your new dance. I talked to the person who directs those concerts, and she says that, at the end of the concert, we are going to move the audience out of the music room and into the main hall for the dance. That should serve to let everyone see well, and also let them stretch their legs.

Will there be four dancers, or six?

Can you write me a little blurb about your dance (i.e., based on the Lichfield tradition, written for X number of dancers, etc.), so I can send it out to the Ocean Orchestra mailing list?

Voting deadline; now"\n?>\n