<?
$details = "We will be performing on stage for Ocean Orchestra, which is slated for 12-1 on the Potomac Palisades Stage on SUNDAY.  That means you should get to the stage no later than 11:45 am; parking WILL BE HELL so plan accordingly!  Carpool if possible.  Call Alan at (202) 258-9289 if there is any trouble on the way there.

After that, we will do our usual guerilla efforts rain or shine throughout the festival site and repair to the pub when we\\\'ve had enough.  Pub suggestions are well received: email the fbmm email list (Last year was Royal Mile).

Go to the FSGW website for more info:
http://ceimd.com/php/public.php?Org=fsgw&ProgramID=10&NoTitle=1"
?>
